services:
  postgres:
    image: postgres:16
    container_name: postgres_container
    environment:
      POSTGRES_USER: twenty1
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: delivery
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    image: leewon2/backend-image
    container_name: backend-container
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/delivery
      SPRING_DATASOURCE_USERNAME: twenty1
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      AI_API_KEY: ${AI_API_KEY}
    ports:
      - "8080:8080"

volumes:
  postgres_data:
